### ISSUE TITLE
Nuget Package Update ?

### ISSUE THREAD

**Issue by victorperez2911** [showplan/showplan-dotnet#1]
Hello.

I would like to test your project.

I realized that in December 2020 a commit was made, however the nuget is still with a September 2020 version.

Do you have plans to update the package?

**Comment by phil-scott-78** [comment]
Hey Victor, if you check the commits the just recent updates just roll back some changes so get back to the September state. I just didn't want to lose the history so the commits remain.

Let me know if you have any questions or comments, I myself haven't found the time to even consume it for my side project so it is definitely in alpha state.
